/**
 * GENERATED by scripts/prepare-intro-assets.mjs — do not edit.
 * Run `node scripts/prepare-assets.mjs && node scripts/prepare-intro-assets.mjs`.
 */

export const INTRO_DATA = {
  "atlas": {
    "width": 384,
    "height": 768,
    "range": 420,
    "pow": 0.4
  },
  "markRect": {
    "x": 0.25012345679012343,
    "y": 0.03999999999999996,
    "w": 0.4997530864197531,
    "h": 0.92
  },
  "maxPoreRadius": 10.357,
  "poreCount": 64,
  "ramp": [
    [
      0.8273,
      0.9248,
      0.0307
    ],
    [
      0.7045,
      0.9437,
      0.0852
    ],
    [
      0.4097,
      0.9251,
      0.1995
    ],
    [
      0.1802,
      0.8855,
      0.3368
    ],
    [
      0.0253,
      0.8521,
      0.5207
    ],
    [
      0.0013,
      0.758,
      0.591
    ]
  ],
  "assets": {
    "atlas": "/intro/sdf-atlas.webp",
    "mark": {
      "src": "/brand/v5-mark.webp",
      "width": 255,
      "height": 940
    },
    "wordmark": {
      "src": "/brand/v5-wordmark.webp",
      "width": 900,
      "height": 95
    }
  }
} as const;

export const LOCKUP = {
  "composed": {
    "width": 1400,
    "height": 437
  },
  "mark": {
    "x": 0.011564,
    "y": 0.037037,
    "w": 0.078381,
    "h": 0.925926
  },
  "wordmark": {
    "x": 0.165114,
    "y": 0.361111,
    "w": 0.823322,
    "h": 0.277778
  },
  "vertical": {
    "markAspect": 0.271159,
    "wordmarkAspect": 9.493506,
    "wordmarkHeight": 0.06327,
    "gap": 0.057518
  }
} as const;
